### ISSUE TITLE
可以加入羊群，但是不能加次数

### ISSUE THREAD

**Issue by louavo** [ltxhhz/sheep-sheep#1]

**Comment by ltxhhz** [comment]
我刚试完，目前还有效，可以检查下你的t值

![image](https://user-images.githubusercontent.com/51697596/191483959-687b04c4-3f0f-4967-8a64-48d4f17d8d3a.png)

![image](https://user-images.githubusercontent.com/51697596/191483864-d366e7a4-ec5f-4aae-8ea1-bf7cbdfa0613.png)

![image](https://user-images.githubusercontent.com/51697596/191483430-9a2fa2e3-8705-4806-b947-f94a261b968d.png)

**Comment by louavo** [comment]
现在可以了，刚才就是运行了没加次数
