### ISSUE TITLE
用时和等待这个是怎么计算的

### ISSUE THREAD

**Issue by louavo** [ltxhhz/sheep-sheep#2]

**Comment by ltxhhz** [comment]
请查看[源码](https://github.com/ltxhhz/sheep-sheep/blob/master/index.js)

**Comment by louavo** [comment]
看不懂才问的

**Comment by louavo** [comment]
可以详细说下吗大佬求求

**Comment by ltxhhz** [comment]
这个只是随机数，用了[lodash](https://www.npmjs.com/package/lodash)库

另外这属于你自己的问题，不应该提issue,努力提升自己才是最重要的

**Comment by louavo** [comment]
好的谢谢大佬

**Comment by louavo** [comment]
麻烦你了是我的问题，给你抱歉了。

**Comment by ltxhhz** [comment]
好的
